config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :ciudads
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ciudad.rb
class Ciudad < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  belongs_to :Ciudad
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ciudads_controller.rb
class CiudadsController < ApplicationController
  before_action :set_ciudad, only: [:show, :edit, :update, :destroy]

  # GET /ciudads
  # GET /ciudads.json
  def index
    @ciudads = Ciudad.all
  end

  # GET /ciudads/1
  # GET /ciudads/1.json
  def show
  end

  # GET /ciudads/new
  def new
    @ciudad = Ciudad.new
  end

  # GET /ciudads/1/edit
  def edit
  end

  # POST /ciudads
  # POST /ciudads.json
  def create
    @ciudad = Ciudad.new(ciudad_params)

    respond_to do |format|
      if @ciudad.save
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully created.' }
        format.json { render :show, status: :created, location: @ciudad }
      else
        format.html { render :new }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ciudads/1
  # PATCH/PUT /ciudads/1.json
  def update
    respond_to do |format|
      if @ciudad.update(ciudad_params)
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ciudad }
      else
        format.html { render :edit }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ciudads/1
  # DELETE /ciudads/1.json
  def destroy
    @ciudad.destroy
    respond_to do |format|
      format.html { redirect_to ciudads_url, notice: 'Ciudad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ciudad
      @ciudad = Ciudad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ciudad_params
      params.require(:ciudad).permit(:nombre, :habitantes)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nombres, :apellidos, :telefono, :salario, :Ciudad_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ciudads_helper.rb
module CiudadsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/ciudads/_form.html.erb
<%= form_with(model: ciudad, local: true) do |form| %>
  <% if ciudad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ciudad.errors.count, "error") %> prohibited this ciudad from being saved:</h2>

      <ul>
        <% ciudad.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :habitantes %>
    <%= form.text_field :habitantes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ciudads/edit.html.erb
<h1>Editing Ciudad</h1>

<%= render 'form', ciudad: @ciudad %>

<%= link_to 'Show', @ciudad %> |
<%= link_to 'Back', ciudads_path %>

app/views/ciudads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ciudads</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Habitantes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ciudads.each do |ciudad| %>
      <tr>
        <td><%= ciudad.nombre %></td>
        <td><%= ciudad.habitantes %></td>
        <td><%= link_to 'Show', ciudad %></td>
        <td><%= link_to 'Edit', edit_ciudad_path(ciudad) %></td>
        <td><%= link_to 'Destroy', ciudad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ciudad', new_ciudad_path %>

app/views/ciudads/new.html.erb
<h1>New Ciudad</h1>

<%= render 'form', ciudad: @ciudad %>

<%= link_to 'Back', ciudads_path %>

app/views/ciudads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ciudad.nombre %>
</p>

<p>
  <strong>Habitantes:</strong>
  <%= @ciudad.habitantes %>
</p>

<%= link_to 'Edit', edit_ciudad_path(@ciudad) %> |
<%= link_to 'Back', ciudads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"> </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>

  <div class="field">
    <%= form.label :salario %>
    <%= form.text_field :salario %>
  </div>

  <div class="field">
    <%= form.label :Ciudad_id %>
    <%= form.select :Ciudad_id, options_for_select(Ciudad.all.map{|s|[s.nombre, s.id]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Telefono</th>
      <th>Salario</th>
      <th>Ciudad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombres %></td>
        <td><%= usuario.apellidos %></td>
        <td><%= usuario.telefono %></td>
        <td><%= usuario.salario %></td>
        
        <td><%= usuario.Ciudad.id.to_s+" - "+usuario.Ciudad.nombre %></td>
        <td><%= link_to 'Show', usuario,:class => "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario), :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: {confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @usuario.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @usuario.apellidos %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @usuario.telefono %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @usuario.salario %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @usuario.Ciudad_id %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Regresar', usuarios_path %>